### ISSUE TITLE
strange issue - removeusersfromall groups

### ISSUE THREAD

**Issue by baha00** [michevnew/PowerShell#12]
I am using connect to exchange via secureapp model. 

Connect-ExchangeOnline -CertificateFilePath "C:\temp\mycert.pfx" -CertificatePassword (ConvertTo-SecureString -String "somepass" -AsPlainText -Force) -AppID $app_id -Organization "myorg.something"

Azure app has role exchange admin added,  but removing from o365 groups doesn't work, drops out exception: 

System.Management.Automation.RemoteException: Failed to retrieve executing user. Please try again later.

It removes user from security Groups without any errors

**Comment by michevnew** [comment]
Some of the Unified Group cmdlets are not fully supported for CBA, and it's sure taking a lot of time for Microsoft to fix them. I'll update the script to use direct Graph queries eventually, until then connect via the "regular" method.
