### ISSUE TITLE
What about external Sharepoint sites and libraries

### ISSUE THREAD

**Issue by FGRoy** [michevnew/PowerShell#2]
Hey Vasil, nice piece of work all good from the current version, more than an issue a functionality request :) .... will it be possible to integrate with exporting library permissions for external users? Since we have the API access, we currently use a PS Script that will do this but no Graph experts and only online PNP module seems to support token access. Would this be suitable for GRAPH? 

$SPOSites = @(Get-SPOSite -Limit ALL)
foreach($site in $SPOSites){
$Users = @(Get-SPOExternalUser -siteurl $site.Url)
foreach($user in $users){
               $Obj = [PSCustomObject]@{SiteCollectionUrl=$site.Url
                                        DisplayName=$user.DisplayName
                                        Email=$user.Email
                                        AcceptedAs=$user.AcceptedAs
                                        JoinDate=$user.WhenCreated
                                        InvitedBy= $user.InvitedBy}
                $result += $obj                         
                } # End foreach User
} # End foreach Site
$result | Export-Csv -Path $ExportPath

Thanks

**Comment by michevnew** [comment]
Addressed in those scripts:

https://github.com/michevnew/PowerShell/blob/master/Graph_SPO_shared_files.ps1
https://github.com/michevnew/PowerShell/blob/master/Graph_SPO_shared_files1.ps1
