### ISSUE TITLE
Unattended

### ISSUE THREAD

**Issue by MWJ1m** [michevnew/PowerShell#20]
Howdy - the remove_User_All_Groups.. script can't be used by unattended scripts that use more modern app based authentication.  I sent over a pull request to fix it.  Probably should have two versions now that I think of it - one for interactive admin like what you had and a separate file for use when using unattended scripts that doesn't have the connection prompts.

**Comment by michevnew** [comment]
Thanks Patrick. The script is indeed not suitable for unattended use. Why don't you just share the link to the updated script instead, I don't mind having it linked here and on the accompanying blog article.

**Comment by MWJ1m** [comment]
Vasil,
You should see the modified version as a pull request. Let me know if I
messed it up and you don't.

I modified the V2 script to track changes, but probably makes more sense to
name it v3, unattended or the like.

Cheers,
Patrick

**Comment by michevnew** [comment]
I saw the PR, however the proposed changes therein only cater to the unattended scenario, and will break any interactive execution. So I'd prefer to have a separate version for that, and since you've already done the job, I don't mind simply linking to your version of the script :)
